version: 1.0.{build}
image: Visual Studio 2022
configuration:
- Debug
- Release
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
before_build:
  - nuget restore
build:
  verbosity: minimal
artifacts:
- path: src\bin\Release
  name: application
